-- Full PostgreSQL setup for AmyLens (canonical + Module 3 compatibility)
-- Idempotent: uses IF NOT EXISTS and IF NOT FOUND patterns where appropriate.
-- Run this as a DB superuser (or a user with CREATE EXTENSION, CREATE TABLE privileges).

-- Enable useful extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- Canonical UUID-based schema (preferred)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  display_name TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS varieties (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS devices (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ssaid TEXT NOT NULL UNIQUE,
  hardware_identity TEXT NOT NULL,
  workspace_assignment TEXT,
  health_status TEXT NOT NULL DEFAULT 'Unknown',
  approved BOOLEAN NOT NULL DEFAULT false,
  denied BOOLEAN NOT NULL DEFAULT false,
  approved_by UUID REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  denied_by UUID REFERENCES users(id),
  denied_at TIMESTAMPTZ,
  last_seen_at TIMESTAMPTZ,
  device_label TEXT,
  registered_at TIMESTAMPTZ,
  status TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS device_users (
  device_id UUID REFERENCES devices(id) ON DELETE CASCADE,
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (device_id, user_id)
);

CREATE TABLE IF NOT EXISTS sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_code TEXT NOT NULL UNIQUE,
  device_id UUID REFERENCES devices(id),
  user_id UUID REFERENCES users(id),
  variety TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'new',
  trial_stage TEXT,
  season TEXT,
  captured_at TIMESTAMPTZ NOT NULL,
  submitted_at TIMESTAMPTZ,
  amylose_class TEXT,
  confidence_score NUMERIC(6,4),
  grain_length NUMERIC(8,2),
  grain_shape TEXT,
  percent_acceptability NUMERIC(5,2),
  image_hash TEXT,
  review_state TEXT DEFAULT 'pending',
  reviewer_id UUID REFERENCES users(id),
  reviewed_at TIMESTAMPTZ,
  review_note TEXT,
  needs_review BOOLEAN DEFAULT false,
  device_ssid TEXT,
  user_name TEXT,
  verdict TEXT,
  verdict_reason TEXT,
  reviewer_identity TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS session_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID REFERENCES sessions(id) ON DELETE CASCADE,
  action TEXT NOT NULL,
  reviewer_id UUID REFERENCES users(id),
  reviewer_note TEXT,
  reviewed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS export_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  requested_by UUID REFERENCES users(id),
  format TEXT NOT NULL,
  status_filter TEXT,
  variety_filter TEXT,
  date_from DATE,
  date_to DATE,
  record_count INTEGER,
  export_status TEXT NOT NULL DEFAULT 'queued',
  file_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS analytics_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  snapshot_date DATE NOT NULL,
  metric_name TEXT NOT NULL,
  metric_value NUMERIC NOT NULL,
  payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- Module 3 compatibility: legacy table shapes, columns and helper tables
-- These use the same public names where possible but are guarded with IF NOT EXISTS
-- -----------------------------------------------------------------------------

-- Legacy sessions table shape (bigint id) - create only if sessions (bigint) doesn't already exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='sessions_legacy') THEN
    CREATE TABLE public.sessions_legacy (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      amylose_class VARCHAR(255) NOT NULL,
      captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
      confidence_score DOUBLE PRECISION NOT NULL,
      device_ssid VARCHAR(255) NOT NULL,
      image_hash VARCHAR(255) NOT NULL,
      needs_review BOOLEAN NOT NULL DEFAULT false,
      reviewer_identity VARCHAR(255),
      reviewer_note VARCHAR(255),
      season VARCHAR(255) NOT NULL,
      submitted_at TIMESTAMP WITH TIME ZONE,
      trial_stage VARCHAR(255) NOT NULL,
      user_name VARCHAR(255) NOT NULL,
      variety VARCHAR(255) NOT NULL,
      verdict VARCHAR(255),
      verdict_reason VARCHAR(255)
    );
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping creation of sessions_legacy: %', SQLERRM;
END$$;

-- Legacy devices table shape (bigint id)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='devices_legacy') THEN
    CREATE TABLE public.devices_legacy (
      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      approved_at TIMESTAMP WITH TIME ZONE,
      device_label VARCHAR(255) NOT NULL,
      registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
      ssaid VARCHAR(255) NOT NULL,
      status VARCHAR(255) NOT NULL
    );
  END IF;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'Skipping creation of devices_legacy: %', SQLERRM;
END$$;

-- device_user_names table (module 3 dump)
CREATE TABLE IF NOT EXISTS public.device_user_names (
  device_id BIGINT,
  user_name VARCHAR(255)
);

-- gqris_mirrors table (module 3 reference table)
CREATE TABLE IF NOT EXISTS public.gqris_mirrors (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  amylose_ordinal INTEGER NOT NULL,
  variety VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
-- Indexes and helpers
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_sessions_captured_at ON sessions(captured_at);
CREATE INDEX IF NOT EXISTS idx_sessions_variety ON sessions(variety);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON sessions(status);
CREATE INDEX IF NOT EXISTS idx_devices_ssaid ON devices(ssaid);

-- -----------------------------------------------------------------------------
-- Seed data (safe inserts)
-- -----------------------------------------------------------------------------

-- Varieties (canonical)
INSERT INTO varieties (id, name, is_active)
VALUES
  (gen_random_uuid(), 'IR64', true),
  (gen_random_uuid(), 'Samba', true)
ON CONFLICT (name) DO NOTHING;

-- GQ-RIS mirror rows
INSERT INTO public.gqris_mirrors (amylose_ordinal, variety, year)
VALUES
  (1, 'IR64', 2024),
  (2, 'Samba', 2024)
ON CONFLICT DO NOTHING;

-- Admin user placeholder (replace hash with real bcrypt/argon2 hash)
INSERT INTO users (id, username, password_hash, display_name, role)
VALUES (gen_random_uuid(), 'admin', '$2b$12$REPLACE_WITH_REAL_HASH', 'Administrator', 'admin')
ON CONFLICT (username) DO NOTHING;

-- Example device (canonical) if none exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM devices LIMIT 1) THEN
    INSERT INTO devices (id, ssaid, hardware_identity, workspace_assignment, health_status, registered_at, device_label)
    VALUES (gen_random_uuid(), '550e8400-e29b-41d4-a716-446655440000', 'Demo Device 001', 'Demo Workspace', 'Healthy', now(), 'Demo-001');
  END IF;
END$$;

-- Example session (canonical) if none exist
DO $$
DECLARE
  d_id UUID;
  u_id UUID;
BEGIN
  SELECT id INTO d_id FROM devices LIMIT 1;
  SELECT id INTO u_id FROM users WHERE username='admin' LIMIT 1;
  IF NOT EXISTS (SELECT 1 FROM sessions LIMIT 1) THEN
    INSERT INTO sessions (id, session_code, device_id, user_id, variety, status, captured_at, submitted_at, amylose_class, confidence_score, image_hash, user_name)
    VALUES (gen_random_uuid(), 'SESS-001', d_id, u_id, 'IR64', 'verified', '2024-10-01T09:12:00Z'::timestamptz, '2024-10-01T09:13:00Z'::timestamptz, 'Waxy', 0.92, 'hash1', 'Alice');
  END IF;
END$$;

-- Example legacy device and session rows (bigint) only if legacy tables are empty
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='devices_legacy') THEN
    IF NOT EXISTS (SELECT 1 FROM devices_legacy LIMIT 1) THEN
      INSERT INTO devices_legacy (device_label, registered_at, ssaid, status)
      VALUES ('Legacy Demo', now(), 'LEG-SS-0001', 'PENDING');
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname='public' AND tablename='sessions_legacy') THEN
    IF NOT EXISTS (SELECT 1 FROM sessions_legacy LIMIT 1) THEN
      INSERT INTO sessions_legacy (amylose_class, captured_at, confidence_score, device_ssid, image_hash, needs_review, season, trial_stage, user_name, variety, submitted_at)
      VALUES ('Waxy', now(), 0.92, 'LEG-SS-0001', 'hash1', false, '2024', 'Field', 'Alice', 'IR64', now());
    END IF;
  END IF;
END$$;

-- -----------------------------------------------------------------------------
-- Notes
-- - Replace the admin password hash placeholder with a secure hash before production use.
-- - Consider adding triggers to update `updated_at` on row modifications.
-- - For heavy exports, implement server-side streaming (COPY TO) rather than loading all rows into memory.
-- -----------------------------------------------------------------------------
